# Generated by Django 5.2 on 2025-05-13 19:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_empleado_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Texto de Observacion'),
        ),
    ]
