# Generated by Django 5.2 on 2025-06-14 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='departamento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el departamento está operativo', verbose_name='¿Está activo?'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del departamento (ej: Recursos Humanos)', max_length=50, unique=True, verbose_name='Nombre del Departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='oficina',
            field=models.CharField(blank=True, help_text='Número/identificador de oficina', max_length=10, verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='piso',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de piso donde se ubica', null=True, verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='sigla',
            field=models.CharField(help_text='Sigla identificatoria (ej: RRHH)', max_length=10, unique=True, verbose_name='Sigla'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['nombre'], name='departament_nombre_10b1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['sigla'], name='departament_sigla_160a47_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['activo'], name='departament_activo_b4483a_idx'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('nombre', 'sigla'), name='unique_nombre_sigla'),
        ),
    ]
